
// Sample location data for auto-suggestions

// Sample list of US addresses - in a real app, this would come from an API
export const US_ADDRESSES = [
  "123 Main St, New York, NY 10001",
  "456 Broadway, New York, NY 10002",
  "789 5th Avenue, New York, NY 10003",
  "101 Hollywood Blvd, Los Angeles, CA 90001",
  "202 Sunset Blvd, Los Angeles, CA 90002",
  "303 Rodeo Dr, Beverly Hills, CA 90210",
  "404 Michigan Ave, Chicago, IL 60601",
  "505 State St, Chicago, IL 60602",
  "606 Lake Shore Dr, Chicago, IL 60603",
  "707 Market St, San Francisco, CA 94103",
  "808 Union Square, San Francisco, CA 94108",
  "909 Fisherman's Wharf, San Francisco, CA 94133",
  "1010 Lombard St, San Francisco, CA 94109",
  "1111 Mission St, San Francisco, CA 94103",
  "1212 Powell St, San Francisco, CA 94108",
  "1313 Haight St, San Francisco, CA 94117",
  "1414 Castro St, San Francisco, CA 94114",
  "1515 Valencia St, San Francisco, CA 94110",
  "1616 Divisadero St, San Francisco, CA 94115",
  "1717 Ocean Ave, San Francisco, CA 94112",
  // Additional entries with street addresses
  "123 Peachtree St, Atlanta, GA 30303",
  "456 Piedmont Ave, Atlanta, GA 30308",
  "789 Ponce de Leon Ave, Atlanta, GA 30306",
  "101 First St, Austin, TX 78701",
  "202 Congress Ave, Austin, TX 78701",
  "303 Sixth St, Austin, TX 78701",
  "404 Rainey St, Austin, TX 78701",
  "505 Lavaca St, Austin, TX 78701"
];

// Also include the simpler city/state entries
export const US_CITIES = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "Fort Worth, TX",
  "Columbus, OH",
  "San Francisco, CA",
  "Charlotte, NC",
  "Indianapolis, IN",
  "Seattle, WA",
  "Denver, CO",
  "Washington, DC",
  "Boston, MA",
  "El Paso, TX",
  "Nashville, TN",
  "Detroit, MI",
  "Portland, OR",
  "Memphis, TN",
  "Oklahoma City, OK",
  "Las Vegas, NV",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Sacramento, CA",
  "Mesa, AZ",
  "Kansas City, MO",
  "Atlanta, GA",
  "Long Beach, CA",
  "Colorado Springs, CO",
  "Raleigh, NC",
  "Miami, FL",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tulsa, OK",
  "Cleveland, OH",
  "Wichita, KS",
  "Arlington, TX",
  "New Orleans, LA",
  "Brooklyn, NY",
  "Queens, NY",
  "Manhattan, NY",
  "Bronx, NY",
  "Staten Island, NY"
];

// Combine both for a comprehensive list
export const LOCATIONS = [...US_ADDRESSES, ...US_CITIES];
